INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Spider','124spider',30000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2018 Ford F-350 Dually','18f350ds',85000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2019 Ford Mustang GT500','19gt500',730000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Chevrolet Camaro ZL1 2018','2018zl1',70000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2020 Ford F-250 Super Duty','20f250',34000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Ferrari GTO 599XX','599gtox',1750000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMW7L','750li',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Javelin 1972 AMC','amcj',25000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bentley Ben','bbentayga',184000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bugatti Divo','bdivo',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Buick 1987','BGNX',30000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bentley Mul','BMM',304000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bugatti Veyron','BUGATTI',1300000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Caprice Ls 2013','caprice13',25000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bugatti Chiron','chiron',3000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Bentley 2013','CONTGT13',187000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Chevrolet Corvette ZR1','corvetteZR1',120000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2011 Ford Crownvic CVPI Retired','crownvic',15000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Ford Mustang GT 2018','FMGT',36000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Lexus GS F 2019','gsf',85000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Buick 1970','GSXB',20000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('FORD GT 2017','GT2017',450000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Ferrari GTC4 Lusso','GTCL',300000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2014 Lamborghini Huracan LP610-4','lp610',390000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMWM4','M4F82',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMWM5','m5f90',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMWM6','M6F13',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2004 Mustang Cobra','MGT',27000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Nissan GT R Nismo 2020','nismo20',211000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Nissan Patrol Super Safari 2016','patrolsafari',47000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Schafter','POLSCHAFTER3',325000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2017 Ford Raptor','RAPTOR2017',52000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2019 Lamborghini SC18 Alston','sc18',7000000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Chevrolet Suburban 2016','SUBN',66000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Declasse Drift Tampa V2','TAMPA3',995000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('Nissan Armada Nismo','tulenis',65000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('2017 Ford F-150 Hennessey Velociraptor','velociraptor',350000,'reales');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMWX5','X5E53',10000000,'ultra');
INSERT INTO `vehicles` (`name`,`model`,`price`,`category`) VALUES ('BMWX6','X6M',10000000,'ultra');
